# Generated by Django 4.2.4 on 2023-08-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("1", "Inactive"), ("2", "Active")],
                        default=2,
                        max_length=2,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Users",
        ),
    ]
