# Generated by Django 4.2.4 on 2023-08-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapps", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrow",
            old_name="crated_time",
            new_name="created_time",
        ),
        migrations.RenameField(
            model_name="member",
            old_name="crated_time",
            new_name="created_time",
        ),
        migrations.AlterField(
            model_name="borrow",
            name="updated_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
