# Generated by Django 4.1.10 on 2023-09-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapps', '0002_alter_member_options_alter_member_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
