# Generated by Django 4.2.4 on 2023-08-13 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookapps", "0002_category_delete_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("author", models.CharField(max_length=200)),
                ("publisher", models.CharField(max_length=200)),
                ("published_date", models.DateTimeField()),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookapps.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=200)),
                (
                    "gender",
                    models.CharField(
                        choices=[("1", "Male"), ("2", "Female")],
                        default=1,
                        max_length=2,
                    ),
                ),
                ("email", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("crated_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Borrow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrow_date", models.DateField()),
                ("return_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("1", "pending"), ("2", "returned")],
                        default=1,
                        max_length=2,
                    ),
                ),
                ("crated_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bookapps.books"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookapps.students",
                    ),
                ),
            ],
        ),
    ]
