# Generated by Django 4.2.4 on 2023-08-14 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookapps", "0003_books_students_borrow"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Books",
            new_name="Book",
        ),
        migrations.RenameModel(
            old_name="Students",
            new_name="Student",
        ),
    ]
