# Generated by Django 4.2.4 on 2023-08-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapps', '0004_rename_books_book_rename_students_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Member',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='student',
            new_name='member',
        ),
    ]
