# Generated by Django 4.2.4 on 2023-08-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapps', '0005_rename_student_member_rename_student_borrow_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='category',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
    ]
